package cs355.solution;

/**
 * Created by Daniel on 9/6/14.
 */
public enum CS355State {
    DRAWING_LINE_FIRST_POINT,
    DRAWING_LINE_SECOND_POINT,
    DRAWING_CIRCLE_FIRST_POINT,
    DRAWING_CIRCLE_SECOND_POINT,
    DRAWING_SQUARE_FIRST_POINT,
    DRAWING_SQUARE_SECOND_POINT,
    DRAWING_RECTANGLE_FIRST_POINT,
    DRAWING_RECTANGLE_SECOND_POINT,
    DRAWING_ELLIPSE_FIRST_POINT,
    DRAWING_ELLIPSE_SECOND_POINT,
    DRAWING_TRIANGLE_FIRST_POINT,
    DRAWING_TRIANGLE_SECOND_POINT,
    DRAWING_TRIANGLE_THIRD_POINT
}
